#!/usr/bin/env python3
"""
Tech Spec Agent — conversational agent that interviews you and writes
a technical specification, then optionally creates a GitHub issue.

Usage:
    python agents/tech_spec.py                    # uses current repo
    python agents/tech_spec.py --repo owner/name  # specify repo
    python agents/tech_spec.py --save spec.md     # save to file
"""
from __future__ import annotations
import sys
import argparse
import json
from datetime import datetime
from base import gpt, gpt_stream, gh, current_repo, ensure_labels

SYSTEM = """You are a technical specification writer. Your job is to interview
the user about a feature they want to build and produce a precise, implementable
technical spec.

Interview style:
- Ask one focused question at a time
- Dig into ambiguity: "what exactly do you mean by X?"
- Surface hidden constraints: "what happens when Y fails?"
- Challenge scope: "do you really need Z for v1?"
- Stop when you have enough to write a complete spec

When you have enough information (after 4-8 questions), say exactly:
  READY_TO_WRITE

Then when asked, produce a spec with these sections:
## Overview
## Problem
## User Stories
## Technical Design
## API / Interface
## Data Model
## Edge Cases
## Out of Scope
## Acceptance Criteria
## Implementation Notes"""

SPEC_PROMPT = """Based on our conversation, write a complete technical specification.
Be precise and implementation-ready. An engineer should be able to implement this
without asking questions."""


def interview(repo: str) -> tuple[str, list]:
    """Run the conversational interview. Returns (summary, messages)."""
    print(f"\nTech Spec Agent — {repo}")
    print("Tell me about the feature you want to build.\n")
    print("─" * 60)

    messages = []
    user_input = input("You: ").strip()
    if not user_input:
        sys.exit(0)

    messages.append({"role": "user", "content": user_input})

    while True:
        print("\nAgent: ", end="")
        response = gpt_stream(SYSTEM, messages)
        messages.append({"role": "assistant", "content": response})

        if "READY_TO_WRITE" in response:
            break

        print()
        user_input = input("You: ").strip()
        if not user_input or user_input.lower() in ("done", "exit", "quit"):
            break
        messages.append({"role": "user", "content": user_input})

    return messages


def write_spec(messages: list) -> str:
    """Generate the spec from the conversation."""
    print("\n" + "─" * 60)
    print("Writing specification...\n")
    messages_for_spec = messages + [{"role": "user", "content": SPEC_PROMPT}]
    return gpt_stream(SYSTEM, messages_for_spec[1:])  # skip system, already in gpt_stream


def save_spec(spec: str, path: str) -> None:
    with open(path, "w") as f:
        f.write(f"# Technical Specification\n\n")
        f.write(f"_Generated by Tech Spec Agent on {datetime.now().strftime('%Y-%m-%d %H:%M')}_\n\n")
        f.write(spec)
    print(f"\nSpec saved to: {path}")


def create_github_issue(spec: str, repo: str) -> str:
    """Create a GitHub issue from the spec."""
    # Extract title from first heading after Overview
    title = gpt(
        "Extract a concise issue title (max 60 chars) from this spec. Return only the title, nothing else.",
        spec[:500]
    ).strip().strip('"')

    url = gh(f'issue create --repo {repo} --title "{title}" '
             f'--body "{spec.replace(chr(34), chr(39))}" --label epic')
    return url


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", help="GitHub repo (owner/name). Defaults to current dir.")
    parser.add_argument("--save", help="Save spec to this file path.")
    parser.add_argument("--no-issue", action="store_true", help="Don't create a GitHub issue.")
    args = parser.parse_args()

    repo = args.repo or current_repo()
    ensure_labels(repo)

    messages = interview(repo)
    spec = write_spec(messages)

    if args.save:
        save_spec(spec, args.save)

    if not args.no_issue:
        print("\n" + "─" * 60)
        create_issue = input("Create a GitHub issue from this spec? [Y/n] ").strip().lower()
        if create_issue not in ("n", "no"):
            url = create_github_issue(spec, repo)
            print(f"Issue created: {url}")


if __name__ == "__main__":
    main()
